---
title: CV
name: Hannah
surname: Garcia-Wickstrum
position: "Student"
address: "Ventura, CA"
phone: (805) 760-4030
www: mariecurie.com
email: "hannah_garcia@ucsb.edu"
github: HannahGW
linkedin: HannahGarciaWickstrum
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  vitae::markdowncv:
    theme: kjhealy
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

## Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Master of Environmental Science and Management", "2019-2021", "Bren School of Environmental Science and Management", "Santa Barbara, CA",
  "Bachelor of Science in Biological Sciences", "2014", "University of California, Davis", "Davis, CA",
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

## Master's Research Project

```{r}
tribble(
  ~Title, ~Year, ~Title, ~Desc
  "Project Manager", "2020-2021", "Conservation of Yellow Pine Mixed Conifer Forests in Southern California: A Look Into the Past, Present, and Future", ""
) %>% 
  detailed_entries(Title, Year, Title, Desc)
  
```

## Publications

```{r}
library(dplyr)
knitr::write_bib(c("vitae", "tibble"), "packages.bib")

bibliography_entries("packages.bib") %>%
  arrange(desc(author$family), issued)
```

