---
name: Hannah 
surname: Garcia-Wickstrum
position: "Graduate Student"
address: "319 Walnut Dr., Ventura, CA"
phone: (805) 760-4030
email: "hannah_garcia@ucsb.edu"
github: HannahGW
linkedin: mariecurie
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::hyndman
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Master of Environmental Science and Management", "2019-present", "Bren School of Environemntal Science and Managament", "Santa Barbara, CA",
  "B.S. Biological Science", "2014", "University of California, Davis", "Davis, CA",
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Nobel Prizes

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>% 
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year, 
    Desc
  )
```

# Conservation & Ecological Experience 

```{r}
library(dplyr)
knitr::write_bib(c("vitae", "tibble"), "packages.bib")

bibliography_entries("packages.bib") %>%
  arrange(desc(author$family), issued)
```


# Education & Outreach Experience 


# Teaching Experience